import { Playfair_Display, Inter } from "next/font/google";
import "./globals.css";

const playfair_display = Playfair_Display({
  variable: "--font-playfair_display",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Coffee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${playfair_display.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
